= Docker & Kubernetes

:toc:
:toclevels: 3
:toc-placement!:

toc::[]

== Installation Kubernetes

I'm going to run kubernetes on top of docker  :
Just follow : c.f. http://kubernetes.io/docs/getting-started-guides/docker/

* sudo mkdir /kubernetes
* cd /kubernetes
* ...

== Exemple d'utilisation de Kubernetes

* Utiliser un serveur nginx

  kubectl run nginx --image=nginx --port=80
  kubectl expose deployment nginx --port=80 

* Pour connaitre l'adresse IP de nginx:

  ip=$(kubectl get svc nginx --template={{.spec.clusterIP}})
  echo $ip

* Arrêter l'application :

  kubectl delete deployment,service nginx

* Exemple 1 : démarrer 2 process nginx

  kubectl run my-nginx --image=nginx --replicas=2 --port=80 --expose --service-overrides='{ "spec": { "type": "LoadBalancer" } }

** on peut vérifier qu'ils sont démarrés:

  kubectl get po

** Récupérer l'adress IP :

  kubectl get service/my-nginx

** Arrêt application

  kubectl delete deployment,service my-nginx


== Notes

tuer process avec docker
----
# retourne liste des container (cid) docker
docker ps
# liste les process du container
docker top <cid>
# tue le process pid d'un container.
sudo docker exec <cid> kill -9 <pid>
----

== Exemple

Pour les 2 replicas nommées my-nginx.

. Liste des containers

  docker ps

  ubuntu@ubuntu-VirtualBox:/kubernetes$ docker ps |grep my-ngin
  e36bff4833cd        nginx                                             "nginx -g 'daemon off"   About a minute ago   Up About a minute                       k8s_my-nginx.2c3f2943_my-nginx-3800858182-8530v_default_f5a8079f-1535-11e6-b26f-080027447db5_384d4d5b
  fa76a49cefaa        nginx                                             "nginx -g 'daemon off"   13 minutes ago       Up 13 minutes                           k8s_my-nginx.2c3f2943_my-nginx-3800858182-76c25_default_f5a81a4a-1535-11e6-b26f-080027447db5_25c0c557
  4b5d3beb4b9b        gcr.io/google_containers/pause:2.0                "/pause"                 13 minutes ago       Up 13 minutes                           k8s_POD.cf58006d_my-nginx-3800858182-76c25_default_f5a81a4a-1535-11e6-b26f-080027447db5_635a3d55
  3cb92d39c3b0        gcr.io/google_containers/pause:2.0                "/pause"                 13 minutes ago       Up 13 minutes                           k8s_POD.cf58006d_my-nginx-3800858182-8530v_default_f5a8079f-1535-11e6-b26f-080027447db5_868e1015

. docker top e36bff4833cd

  ubuntu@ubuntu-VirtualBox:/kubernetes$ docker top e36bff4833cd
  UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
  root                14503               14492               0                   18:12               ?                   00:00:00            nginx: master process nginx -g daemon off;
  syslog              14511               14503               0                   18:12               ?                   00:00:00            nginx: worker process

. sudo kill -9 14503
. kubectl get pod

  NAME                        READY     STATUS    RESTARTS   AGE
  k8s-etcd-127.0.0.1          1/1       Running   0          50m
  k8s-master-127.0.0.1        4/4       Running   4          50m
  k8s-proxy-127.0.0.1         1/1       Running   0          50m
  my-nginx-3800858182-76c25   1/1       Running   0          14m
  my-nginx-3800858182-8530v   0/1       Error     1          14m

. kubectl get pod

  NAME                        READY     STATUS             RESTARTS   AGE
  k8s-etcd-127.0.0.1          1/1       Running            0          50m
  k8s-master-127.0.0.1        4/4       Running            4          50m
  k8s-proxy-127.0.0.1         1/1       Running            0          50m
  my-nginx-3800858182-76c25   1/1       Running            0          15m
  my-nginx-3800858182-8530v   0/1       CrashLoopBackOff   1          15m

. kubectl get pod

  NAME                        READY     STATUS    RESTARTS   AGE
  k8s-etcd-127.0.0.1          1/1       Running   0          50m
  k8s-master-127.0.0.1        4/4       Running   4          51m
  k8s-proxy-127.0.0.1         1/1       Running   0          50m
  my-nginx-3800858182-76c25   1/1       Running   0          15m
  my-nginx-3800858182-8530v   1/1       Running   2          15m


== Docker & Spring Boot

see https://spring.io/guides/gs/spring-boot-docker/

some commands :

* docker run -p <host-port>:<container-port> gonzalad/gs-spring-boot-docker +
  exemple: docker run -p 8081:8080 gonzalad/gs-spring-boot-docker
* docker images
* docker ps
* ? docker rm <cid?>

TODO : créer manuellement une image docker, la tager, l'uploader dans repo do+cker

TODO : faire la même chose avec build.gradle

== Docker

=== Installation : https://docs.docker.com/linux/step_one/

=== Créer son image

* Créer un fichier Dockerfile
* Saisir

  FROM docker/whalesay:latest
  RUN apt-get -y update && apr-get -y install fortunes
  CMD /usr/games/fortune -a |cowsay

* Dans le fichier précédent :
** FROM indique l'image docker servant de base
** RUN est exécuté lors de la création de l'image
** CMD est exécuté à chaque exécution de l'image
* docker build -t docker-whale. +
  Construit l'image à partir du fichier Dockerfile et la nomme docker-whale +
  docker images montre l'image. +
  Exemple :
** docker run dowker-whale +
   Exécute l'image
** partager l'image sur dockerhub
*** faire docker images et repérer l'identifiant

    REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
    docker-whale                               latest              c50a94d1d644        8 minutes ago       274.5 MB
    gonzalad/gs-spring-boot-docker             latest              b6c1a38e7e0b        9 days ago          194.4 MB

*** tager l'image en préfixant avec l'id de son compte :
      docker tag c50a94d1d644 gonzalad/docker-whale:latest
      Si on refait un docker images, ça donne :

    REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
    docker-whale                               latest              c50a94d1d644        12 minutes ago      274.5 MB
    gonzalad/docker-whale                      latest              c50a94d1d644        12 minutes ago      274.5 MB
    gonzalad/gs-spring-boot-docker             latest              b6c1a38e7e0b        9 days ago          194.4 MB
  
*** docker login --username=gonzalad 
*** docker push gonzalad/docker-whale
*** vérification
**** pour vérifier, nous allons supprimer les images locales

  docker rmi -f  c50a94d1d644 (ou docker rmi -f gonzalad/docker-whale et docker rmi -f docker-whale)

**** docker run gonzalad/docker-whale

## Pour aller plus loin

 * Arrêter tous les process en cours

   docker stop $(docker ps -a --format={{.Names}})

 * Supprimer tous les process terminés

   docker rm $(docker ps -a -f status=exited --format={{.Names}})

 * Supprimer tous les process

   docker rm $(docker ps -a --format={{.Names}})

 * To list all running and stopped containers

   docker ps -a

 * To list all running containers (just stating the obvious and also example use of -f filtering option)

  docker ps -a -f status=running

 * To list all running and stopped containers, showing only their container id

  docker ps -aq

 * To remove all containers that are NOT running

  docker rm `docker ps -aq -f status=exited`

= Liens, tutoriaux et Références

* https://github.com/arun-gupta/kubernetes-java-sample/
* https://docs.docker.com/linux/last_page/
* https://goldmann.pl/blog/2014/07/18/logging-with-the-wildfly-docker-image/
* https://hub.docker.com/r/jboss/wildfly/~/dockerfile/
* mvn docker:build
* http://ricostacruz.com/cheatsheets/docker.html

divers:
* https://speakerdeck.com/saturnism/2015-spring-io-barcelona-spring-boot-microservices-container-kubernetes-how-to
* https://speakerdeck.com/saturnism/2015-springone-2gx-java-based-microservices-and-kubernetes-how-to
* https://spring.io/blog/2015/10/19/springone2gx-2015-replay-spring-boot-micro-services-containers-and-kubernetes-how-to
* https://www.infoq.com/presentations/spring-boot-microservices


# Microservices

## Logs

Solution : use Elastisearch, Kibana, Logstash and filebeat.

## Monitoring

Exemples :
 * http://www.hawkular.org/docs/overview.html